version: 2
updates:
  - package-ecosystem: maven
    directory: "/stock-management-eventstore"
    schedule:
      interval: daily
      time: '21:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  
  - package-ecosystem: maven
    directory: "/stock-management-traditional"
    schedule:
      interval: daily
      time: '21:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
